### ISSUE TITLE
Project Peer Review 

### ISSUE THREAD

**Issue by moguchi1** [acorreag/Project#1]
Technical Suggestions 
1. It may be better if you put the border for each title in navigation bar so the title of each page could look more clearly. Also I wonder the button on the sitemap page... 

2. Only page 3's youtube video has a Javascript of enlarge ( I assume you are working on this right now). I would put the enlarge function on each style example pictures below on every page so that viewers can explore the style more easily and clearly. 

Content Suggestion 
1. It may be better if you place a link to go next page on the bottom right corner of the page and a link to go back to index page on the bottom left corner of the page. After the viewer reads each page, it may be convenient for them to just click the link at the bottom of each page rather than scrolling up to find the navigation bar. Something like " <--- back to Homepage"?? 

2. You may explain why you listed tattoo shop in Boston. You may be able to introduce a little bit of yourself or tattoo shops in Boston because lists of tattoo shops were suddenly listed on the bottom of index page. Also, page 3 does not have a headline "style examples" above the style example pictures. 

Overall, I love your website. It has pretty good amounts of content and information about tattoos and its styles. I like the examples you provide for each style. I like that each page follow same format and consistency, and gif of index page is so cool. Great work.

**Comment by acorreag** [comment]
Hey there, 

Yes - I was still in the process of a few things (including that random button on sitemap and video enlargement). 

I will highly consider your content suggestions -- I think they're great ideas. 

Thanks for the feedback!
