### ISSUE TITLE
André Feedback

### ISSUE THREAD

**Issue by SlinkierCone** [acorreag/Project#2]
REALLY COOL WEBSITE :)

Content Feedback:

1.
https://github.com/acorreag/Project/blob/fa1f40fd43f5cc30ccf046db2d4e3548e9027d79/index.html#L26
Maybe slow down the image a little bit, I think it would look a bit better (Personal Opinion :)) 

2.
https://github.com/acorreag/Project/blob/fa1f40fd43f5cc30ccf046db2d4e3548e9027d79/index.html#L95
Would be really cool if you could make the phone numbers live links. (So that when I click on them it gives me the option to call)

3. I would make the "TATTOO EDU" link in the header go white like the other links when the user hovers over it. 

Code Feedback:

1. 
https://github.com/acorreag/Project/blob/fa1f40fd43f5cc30ccf046db2d4e3548e9027d79/page1.html#L50
I believe the "width = "100%" is not a valid input in this section. 

2. https://github.com/acorreag/Project/blob/fa1f40fd43f5cc30ccf046db2d4e3548e9027d79/contact.html#L39
I believe it should be (label for = "product") not (label for = "style") so that when you click on the question it take you to the response box.

**Comment by acorreag** [comment]
Super helpful feedback, Andre. You definitely hit on minor details that flew above my help. I appreciate the comments!
